interface CountryOption {
  label: string;
  value: string;
  phoneCode: string;
}

const CountryOption: CountryOption[] = [
  { label: "Afghanistan (+93)", value: "AF", phoneCode: "+93" },
  { label: "Albania (+355)", value: "AL", phoneCode: "+355" },
  { label: "Algeria (+213)", value: "DZ", phoneCode: "+213" },
  { label: "American Samoa (+1-684)", value: "AS", phoneCode: "+1-684" },
  { label: "Andorra (+376)", value: "AD", phoneCode: "+376" },
  { label: "Angola (+244)", value: "AO", phoneCode: "+244" },
  { label: "Anguilla (+1-264)", value: "AI", phoneCode: "+1-264" },
  { label: "Antarctica (+672)", value: "AQ", phoneCode: "+672" },
  { label: "Antigua and Barbuda (+1-268)", value: "AG", phoneCode: "+1-268" },
  { label: "Argentina (+54)", value: "AR", phoneCode: "+54" },
  { label: "Armenia (+374)", value: "AM", phoneCode: "+374" },
  { label: "Aruba (+297)", value: "AW", phoneCode: "+297" },
  { label: "Australia (+61)", value: "AU", phoneCode: "+61" },
  { label: "Austria (+43)", value: "AT", phoneCode: "+43" },
  { label: "Azerbaijan (+994)", value: "AZ", phoneCode: "+994" },
  { label: "Bahamas (+1-242)", value: "BS", phoneCode: "+1-242" },
  { label: "Bahrain (+973)", value: "BH", phoneCode: "+973" },
  { label: "Bangladesh (+880)", value: "BD", phoneCode: "+880" },
  { label: "Barbados (+1-246)", value: "BB", phoneCode: "+1-246" },
  { label: "Belarus (+375)", value: "BY", phoneCode: "+375" },
  { label: "Belgium (+32)", value: "BE", phoneCode: "+32" },
  { label: "Belize (+501)", value: "BZ", phoneCode: "+501" },
  { label: "Benin (+229)", value: "BJ", phoneCode: "+229" },
  { label: "Bermuda (+1-441)", value: "BM", phoneCode: "+1-441" },
  { label: "Bhutan (+975)", value: "BT", phoneCode: "+975" },
  { label: "Bolivia (+591)", value: "BO", phoneCode: "+591" },
  { label: "Bosnia and Herzegovina (+387)", value: "BA", phoneCode: "+387" },
  { label: "Botswana (+267)", value: "BW", phoneCode: "+267" },
  { label: "Brazil (+55)", value: "BR", phoneCode: "+55" },
  { label: "Brunei (+673)", value: "BN", phoneCode: "+673" },
  { label: "Bulgaria (+359)", value: "BG", phoneCode: "+359" },
  { label: "Burkina Faso (+226)", value: "BF", phoneCode: "+226" },
  { label: "Burundi (+257)", value: "BI", phoneCode: "+257" },
  { label: "Cambodia (+855)", value: "KH", phoneCode: "+855" },
  { label: "Cameroon (+237)", value: "CM", phoneCode: "+237" },
  { label: "Canada (+1)", value: "CA", phoneCode: "+1" },
  { label: "Cape Verde (+238)", value: "CV", phoneCode: "+238" },
  { label: "Cayman Islands (+1-345)", value: "KY", phoneCode: "+1-345" },
  { label: "Central African Republic (+236)", value: "CF", phoneCode: "+236" },
  { label: "Chad (+235)", value: "TD", phoneCode: "+235" },
  { label: "Chile (+56)", value: "CL", phoneCode: "+56" },
  { label: "China (+86)", value: "CN", phoneCode: "+86" },
  { label: "Christmas Island (+61)", value: "CX", phoneCode: "+61" },
  { label: "Cocos Islands (+61)", value: "CC", phoneCode: "+61" },
  { label: "Colombia (+57)", value: "CO", phoneCode: "+57" },
  { label: "Comoros (+269)", value: "KM", phoneCode: "+269" },
  { label: "Cook Islands (+682)", value: "CK", phoneCode: "+682" },
  { label: "Costa Rica (+506)", value: "CR", phoneCode: "+506" },
  { label: "Croatia (+385)", value: "HR", phoneCode: "+385" },
  { label: "Cuba (+53)", value: "CU", phoneCode: "+53" },
  { label: "Curacao (+599)", value: "CW", phoneCode: "+599" },
  { label: "Cyprus (+357)", value: "CY", phoneCode: "+357" },
  { label: "Czech Republic (+420)", value: "CZ", phoneCode: "+420" },
  {
    label: "Democratic Republic of the Congo (+243)",
    value: "CD",
    phoneCode: "+243",
  },
  { label: "Denmark (+45)", value: "DK", phoneCode: "+45" },
  { label: "Djibouti (+253)", value: "DJ", phoneCode: "+253" },
  { label: "Dominica (+1-767)", value: "DM", phoneCode: "+1-767" },
  { label: "Dominican Republic (+1-809)", value: "DO", phoneCode: "+1-809" },
  { label: "East Timor (+670)", value: "TL", phoneCode: "+670" },
  { label: "Ecuador (+593)", value: "EC", phoneCode: "+593" },
  { label: "Egypt (+20)", value: "EG", phoneCode: "+20" },
  { label: "El Salvador (+503)", value: "SV", phoneCode: "+503" },
  { label: "Equatorial Guinea (+240)", value: "GQ", phoneCode: "+240" },
  { label: "Eritrea (+291)", value: "ER", phoneCode: "+291" },
  { label: "Estonia (+372)", value: "EE", phoneCode: "+372" },
  { label: "Ethiopia (+251)", value: "ET", phoneCode: "+251" },
  { label: "Falkland Islands (+500)", value: "FK", phoneCode: "+500" },
  { label: "Faroe Islands (+298)", value: "FO", phoneCode: "+298" },
  { label: "Fiji (+679)", value: "FJ", phoneCode: "+679" },
  { label: "Finland (+358)", value: "FI", phoneCode: "+358" },
  { label: "France (+33)", value: "FR", phoneCode: "+33" },
  { label: "French Guiana (+594)", value: "GF", phoneCode: "+594" },
  { label: "French Polynesia (+689)", value: "PF", phoneCode: "+689" },
  { label: "Gabon (+241)", value: "GA", phoneCode: "+241" },
  { label: "Gambia (+220)", value: "GM", phoneCode: "+220" },
  { label: "Georgia (+995)", value: "GE", phoneCode: "+995" },
  { label: "Germany (+49)", value: "DE", phoneCode: "+49" },
  { label: "Ghana (+233)", value: "GH", phoneCode: "+233" },
  { label: "Gibraltar (+350)", value: "GI", phoneCode: "+350" },
  { label: "Greece (+30)", value: "GR", phoneCode: "+30" },
  { label: "Greenland (+299)", value: "GL", phoneCode: "+299" },
  { label: "Grenada (+1)", value: "GD", phoneCode: "+1" },
  { label: "Guadeloupe (+590)", value: "GP", phoneCode: "+590" },
  { label: "Guam (+1)", value: "GU", phoneCode: "+1" },
  { label: "Guatemala (+502)", value: "GT", phoneCode: "+502" },
  { label: "Guernsey (+44)", value: "GG", phoneCode: "+44" },
  { label: "Guinea (+224)", value: "GN", phoneCode: "+224" },
  { label: "Guinea-Bissau (+245)", value: "GW", phoneCode: "+245" },
  { label: "Guyana (+592)", value: "GY", phoneCode: "+592" },
  { label: "Haiti (+509)", value: "HT", phoneCode: "+509" },
  { label: "Honduras (+504)", value: "HN", phoneCode: "+504" },
  { label: "Hong Kong (+852)", value: "HK", phoneCode: "+852" },
  { label: "Hungary (+36)", value: "HU", phoneCode: "+36" },
  { label: "Iceland (+354)", value: "IS", phoneCode: "+354" },
  { label: "India (+91)", value: "IN", phoneCode: "+91" },
  { label: "Indonesia (+62)", value: "ID", phoneCode: "+62" },
  { label: "Iran (+98)", value: "IR", phoneCode: "+98" },
  { label: "Iraq (+964)", value: "IQ", phoneCode: "+964" },
  { label: "Ireland (+353)", value: "IE", phoneCode: "+353" },
  { label: "Isle of Man (+44)", value: "IM", phoneCode: "+44" },
  { label: "Israel (+972)", value: "IL", phoneCode: "+972" },
  { label: "Italy (+39)", value: "IT", phoneCode: "+39" },
  { label: "Jamaica (+1)", value: "JM", phoneCode: "+1" },
  { label: "Japan (+81)", value: "JP", phoneCode: "+81" },
  { label: "Jersey (+44)", value: "JE", phoneCode: "+44" },
  { label: "Jordan (+962)", value: "JO", phoneCode: "+962" },
  { label: "Kazakhstan (+7)", value: "KZ", phoneCode: "+7" },
  { label: "Kenya (+254)", value: "KE", phoneCode: "+254" },
  { label: "Kiribati (+686)", value: "KI", phoneCode: "+686" },
  { label: "Kuwait (+965)", value: "KW", phoneCode: "+965" },
  { label: "Kyrgyzstan (+996)", value: "KG", phoneCode: "+996" },
  { label: "Laos (+856)", value: "LA", phoneCode: "+856" },
  { label: "Latvia (+371)", value: "LV", phoneCode: "+371" },
  { label: "Lebanon (+961)", value: "LB", phoneCode: "+961" },
  { label: "Lesotho (+266)", value: "LS", phoneCode: "+266" },
  { label: "Liberia (+231)", value: "LR", phoneCode: "+231" },
  { label: "Libya (+218)", value: "LY", phoneCode: "+218" },
  { label: "Liechtenstein (+423)", value: "LI", phoneCode: "+423" },
  { label: "Lithuania (+370)", value: "LT", phoneCode: "+370" },
  { label: "Luxembourg (+352)", value: "LU", phoneCode: "+352" },
  { label: "Macao (+853)", value: "MO", phoneCode: "+853" },
  { label: "Macedonia (+389)", value: "MK", phoneCode: "+389" },
  { label: "Madagascar (+261)", value: "MG", phoneCode: "+261" },
  { label: "Malawi (+265)", value: "MW", phoneCode: "+265" },
  { label: "Malaysia (+60)", value: "MY", phoneCode: "+60" },
  { label: "Maldives (+960)", value: "MV", phoneCode: "+960" },
  { label: "Mali (+223)", value: "ML", phoneCode: "+223" },
  { label: "Malta (+356)", value: "MT", phoneCode: "+356" },
  { label: "Marshall Islands (+692)", value: "MH", phoneCode: "+692" },
  { label: "Martinique (+596)", value: "MQ", phoneCode: "+596" },
  { label: "Mauritania (+222)", value: "MR", phoneCode: "+222" },
  { label: "Mauritius (+230)", value: "MU", phoneCode: "+230" },
  { label: "Mayotte (+262)", value: "YT", phoneCode: "+262" },
  { label: "Mexico (+52)", value: "MX", phoneCode: "+52" },
  { label: "Micronesia (+691)", value: "FM", phoneCode: "+691" },
  { label: "Moldova (+373)", value: "MD", phoneCode: "+373" },
  { label: "Monaco (+377)", value: "MC", phoneCode: "+377" },
  { label: "Mongolia (+976)", value: "MN", phoneCode: "+976" },
  { label: "Montenegro (+382)", value: "ME", phoneCode: "+382" },
  { label: "Montserrat (+1)", value: "MS", phoneCode: "+1" },
  { label: "Morocco (+212)", value: "MA", phoneCode: "+212" },
  { label: "Mozambique (+258)", value: "MZ", phoneCode: "+258" },
  { label: "Myanmar (+95)", value: "MM", phoneCode: "+95" },
  { label: "Namibia (+264)", value: "NA", phoneCode: "+264" },
  { label: "Nauru (+674)", value: "NR", phoneCode: "+674" },
  { label: "Nepal (+977)", value: "NP", phoneCode: "+977" },
  { label: "Netherlands (+31)", value: "NL", phoneCode: "+31" },
  { label: "New Caledonia (+687)", value: "NC", phoneCode: "+687" },
  { label: "New Zealand (+64)", value: "NZ", phoneCode: "+64" },
  { label: "Nicaragua (+505)", value: "NI", phoneCode: "+505" },
  { label: "Niger (+227)", value: "NE", phoneCode: "+227" },
  { label: "Nigeria (+234)", value: "NG", phoneCode: "+234" },
  { label: "Niue (+683)", value: "NU", phoneCode: "+683" },
  { label: "Norfolk Island (+672)", value: "NF", phoneCode: "+672" },
  { label: "North Korea (+850)", value: "KP", phoneCode: "+850" },
  { label: "Northern Mariana Islands (+1)", value: "MP", phoneCode: "+1" },
  { label: "Norway (+47)", value: "NO", phoneCode: "+47" },
  { label: "Oman (+968)", value: "OM", phoneCode: "+968" },
  { label: "Pakistan (+92)", value: "PK", phoneCode: "+92" },
  { label: "Palau (+680)", value: "PW", phoneCode: "+680" },
  { label: "Palestine (+970)", value: "PS", phoneCode: "+970" },
  { label: "Panama (+507)", value: "PA", phoneCode: "+507" },
  { label: "Papua New Guinea (+675)", value: "PG", phoneCode: "+675" },
  { label: "Paraguay (+595)", value: "PY", phoneCode: "+595" },
  { label: "Peru (+51)", value: "PE", phoneCode: "+51" },
  { label: "Philippines (+63)", value: "PH", phoneCode: "+63" },
  { label: "Pitcairn (+64)", value: "PN", phoneCode: "+64" },
  { label: "Poland (+48)", value: "PL", phoneCode: "+48" },
  { label: "Portugal (+351)", value: "PT", phoneCode: "+351" },
  { label: "Puerto Rico (+1)", value: "PR", phoneCode: "+1" },
  { label: "Qatar (+974)", value: "QA", phoneCode: "+974" },
  { label: "Réunion (+262)", value: "RE", phoneCode: "+262" },
  { label: "Romania (+40)", value: "RO", phoneCode: "+40" },
  { label: "Russia (+7)", value: "RU", phoneCode: "+7" },
  { label: "Rwanda (+250)", value: "RW", phoneCode: "+250" },
  { label: "Saint Barthélemy (+590)", value: "BL", phoneCode: "+590" },
  { label: "Saint Helena (+290)", value: "SH", phoneCode: "+290" },
  { label: "Saint Kitts and Nevis (+1)", value: "KN", phoneCode: "+1" },
  { label: "Saint Lucia (+1)", value: "LC", phoneCode: "+1" },
  { label: "Saint Martin (+590)", value: "MF", phoneCode: "+590" },
  { label: "Saint Pierre and Miquelon (+508)", value: "PM", phoneCode: "+508" },
  {
    label: "Saint Vincent and the Grenadines (+1)",
    value: "VC",
    phoneCode: "+1",
  },
  { label: "Samoa (+685)", value: "WS", phoneCode: "+685" },
  { label: "San Marino (+378)", value: "SM", phoneCode: "+378" },
  { label: "São Tomé and Príncipe (+239)", value: "ST", phoneCode: "+239" },
  { label: "Saudi Arabia (+966)", value: "SA", phoneCode: "+966" },
  { label: "Senegal (+221)", value: "SN", phoneCode: "+221" },
  { label: "Serbia (+381)", value: "RS", phoneCode: "+381" },
  { label: "Seychelles (+248)", value: "SC", phoneCode: "+248" },
  { label: "Sierra Leone (+232)", value: "SL", phoneCode: "+232" },
  { label: "Singapore (+65)", value: "SG", phoneCode: "+65" },
  { label: "Sint Maarten (+1)", value: "SX", phoneCode: "+1" },
  { label: "Slovakia (+421)", value: "SK", phoneCode: "+421" },
  { label: "Slovenia (+386)", value: "SI", phoneCode: "+386" },
  { label: "Solomon Islands (+677)", value: "SB", phoneCode: "+677" },
  { label: "Somalia (+252)", value: "SO", phoneCode: "+252" },
  { label: "South Africa (+27)", value: "ZA", phoneCode: "+27" },
  { label: "South Korea (+82)", value: "KR", phoneCode: "+82" },
  { label: "South Sudan (+211)", value: "SS", phoneCode: "+211" },
  { label: "Spain (+34)", value: "ES", phoneCode: "+34" },
  { label: "Sri Lanka (+94)", value: "LK", phoneCode: "+94" },
  { label: "Sudan (+249)", value: "SD", phoneCode: "+249" },
  { label: "Suriname (+597)", value: "SR", phoneCode: "+597" },
  { label: "Svalbard and Jan Mayen (+47)", value: "SJ", phoneCode: "+47" },
  { label: "Swaziland (+268)", value: "SZ", phoneCode: "+268" },
  { label: "Sweden (+46)", value: "SE", phoneCode: "+46" },
  { label: "Switzerland (+41)", value: "CH", phoneCode: "+41" },
  { label: "Syria (+963)", value: "SY", phoneCode: "+963" },
  { label: "Taiwan (+886)", value: "TW", phoneCode: "+886" },
  { label: "Tajikistan (+992)", value: "TJ", phoneCode: "+992" },
  { label: "Tanzania (+255)", value: "TZ", phoneCode: "+255" },
  { label: "Thailand (+66)", value: "TH", phoneCode: "+66" },
  { label: "Timor-Leste (+670)", value: "TL", phoneCode: "+670" },
  { label: "Togo (+228)", value: "TG", phoneCode: "+228" },
  { label: "Tokelau (+690)", value: "TK", phoneCode: "+690" },
  { label: "Tonga (+676)", value: "TO", phoneCode: "+676" },
  { label: "Trinidad and Tobago (+1)", value: "TT", phoneCode: "+1" },
  { label: "Tunisia (+216)", value: "TN", phoneCode: "+216" },
  { label: "Turkey (+90)", value: "TR", phoneCode: "+90" },
  { label: "Turkmenistan (+993)", value: "TM", phoneCode: "+993" },
  { label: "Turks and Caicos Islands (+1)", value: "TC", phoneCode: "+1" },
  { label: "Tuvalu (+688)", value: "TV", phoneCode: "+688" },
  { label: "U.S. Virgin Islands (+1)", value: "VI", phoneCode: "+1" },
  { label: "Uganda (+256)", value: "UG", phoneCode: "+256" },
  { label: "Ukraine (+380)", value: "UA", phoneCode: "+380" },
  { label: "United Arab Emirates (+971)", value: "AE", phoneCode: "+971" },
  { label: "Uruguay (+598)", value: "UY", phoneCode: "+598" },
  { label: "Uzbekistan (+998)", value: "UZ", phoneCode: "+998" },
  { label: "Vanuatu (+678)", value: "VU", phoneCode: "+678" },
  { label: "Vatican City (+39)", value: "VA", phoneCode: "+39" },
  { label: "Venezuela (+58)", value: "VE", phoneCode: "+58" },
  { label: "Vietnam (+84)", value: "VN", phoneCode: "+84" },
  { label: "Wallis and Futuna (+681)", value: "WF", phoneCode: "+681" },
  { label: "Western Sahara (+212)", value: "EH", phoneCode: "+212" },
  { label: "Yemen (+967)", value: "YE", phoneCode: "+967" },
  { label: "Zambia (+260)", value: "ZM", phoneCode: "+260" },
  { label: "Zimbabwe (+263)", value: "ZW", phoneCode: "+263" },
];

export { CountryOption };
