import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppProvider } from "@/context/AppProvider";
import { Navbar } from "@/components";
import "antd/dist/reset.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";
import "./globals.css";

// Add all solid icons to the library
library.add(fas);

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="main">
          <AppProvider>
        
            <Navbar />
            <div className="main-content">
              {children}
            </div>
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
